------------------- MODULE MCn4t1f0_tendermint_single_indinv -------------------
\* Generated by Wunderspec v0.136.1.
\* Input file: tendermint_single_indinv.py
\* Date: 2026-07-06T11:40:08Z
\* Input SHA-256:
\*   6b40f0c3d0eb2d8144761764e5a3ed3592d21d9fff585fa7f71f5cff9451dd31
\* Convert parameters:
\*   --to: /home/parallels/devl/apalache-examples/tendermint/MCn4t1f0_tendermint
\*     _single_indinv.tla
\*   --defs: <not used>
\*   --instance: n4_t1_f0
\*   --text-width: 80
\*   --text-indent: 2
\* an instance to run the model checker
EXTENDS Integers, FiniteSets, Sequences

Corr == (0)..(3)
Faulty == {}
N == 4
T == 1
ValidValues == {0, 1}
InvalidValues == {2}
MaxRound == 3
Proposer == [v_v0 \in (0)..(3) |-> v_v0]

VARIABLES
  \* @type: Int -> Int;
  round,
  \* @type: Int -> STEP;
  step,
  \* @type: Int -> Int;
  decision,
  \* @type: Int -> Int;
  locked_value,
  \* @type: Int -> Int;
  locked_round,
  \* @type: Int -> Int;
  valid_value,
  \* @type: Int -> Int;
  valid_round,
  \* @type: Int -> Set({proposal: Int, round: Int, src: Int, valid_round: Int});
  msgs_propose,
  \* @type: Int -> Set({id: Int, kind: VOTEKIND, round: Int, src: Int});
  msgs_prevote,
  \* @type: Int -> Set({id: Int, kind: VOTEKIND, round: Int, src: Int});
  msgs_precommit,
  \* @type: Str;
  last_action

INSTANCE tendermint_single_indinv
================================================================================