----------------------- MODULE tendermint_single_indinv ------------------------
\* Generated by Wunderspec v0.136.1.
\* Input file: tendermint_single_indinv.py
\* Date: 2026-07-05T19:14:06Z
\* Input SHA-256:
\*   6b40f0c3d0eb2d8144761764e5a3ed3592d21d9fff585fa7f71f5cff9451dd31
\* Convert parameters:
\*   --to: /tmp/claude-1000/-home-parallels-devl-apalache-examples/bd421554-ba38
\*     -4cfc-9814-d8e23dfdf561/scratchpad/gen/tendermint_single_indinv.tla
\*   --defs: <auto>
\*   --instance: <none>
\*   --text-width: 80
\*   --text-indent: 2
EXTENDS Integers, FiniteSets, Sequences

CONSTANTS
  \* @type: Set(Int);
  Corr,
  \* @type: Set(Int);
  Faulty,
  \* @type: Int;
  N,
  \* @type: Int;
  T,
  \* @type: Set(Int);
  ValidValues,
  \* @type: Set(Int);
  InvalidValues,
  \* @type: Int;
  MaxRound,
  \* @type: Int -> Int;
  Proposer

VARIABLES
  \* @type: Int -> Int;
  round,
  \* @type: Int -> STEP;
  step,
  \* @type: Int -> Int;
  decision,
  \* @type: Int -> Int;
  locked_value,
  \* @type: Int -> Int;
  locked_round,
  \* @type: Int -> Int;
  valid_value,
  \* @type: Int -> Int;
  valid_round,
  \* @type: Int -> Set({proposal: Int, round: Int, src: Int, valid_round: Int});
  msgs_propose,
  \* @type: Int -> Set({id: Int, kind: VOTEKIND, round: Int, src: Int});
  msgs_prevote,
  \* @type: Int -> Set({id: Int, kind: VOTEKIND, round: Int, src: Int});
  msgs_precommit,
  \* @type: Str;
  last_action

\* @type: (a, b, c, d, e, f, g) => <<a, b, c, d, e, f, g>>;
WSMkTuple7(x0, x1, x2, x3, x4, x5, x6) ==
  <<x0, x1, x2, x3, x4, x5, x6>>

\* 14: if proposer(h_p, round_p) = p then
\* 15:   if validValue_p != nil then
\* 16:     proposal <- validValue_p
\* 17:   else:
\* 18:     proposal <- getValue()
\* 19:   broadcast <PROPOSAL, h_p, round_p, proposal, validRound_p>
\* 20: else:
\* 21:   schedule OnTimeoutPropose(h_p, round_p) ...
\* @type: (Int) => Bool;
InsertProposal(p) ==
  InsertProposal ::
  LET v_cache59 ==
    round[p]
  IN
    /\ (p = Proposer[v_cache59])
    /\ (step[p] = "PROPOSE_OF_STEP")
    /\ \A v_v60 \in msgs_propose[v_cache59]: (p /= v_v60.src)
    /\ /\ \E v \in ValidValues:
            /\ msgs_propose' =
                 [msgs_propose EXCEPT ![v_cache59] =
                   (msgs_propose[v_cache59] \union {[proposal |-> (IF (valid_value[p] /= -1)
                       THEN
                         valid_value[p]
                       ELSE
                         v),
                       round |-> v_cache59,
                       src |-> p,
                       valid_round |-> valid_round[p]]})]
            /\ last_action' = "INSERT_PROPOSAL"

\* 22: upon proposal (v, -1) from proposer while step_p = propose
\* 23:   if valid(v) and (lockedRound_p = -1 or lockedValue_p = v) then
\* 24:     broadcast PREVOTE for v
\* 25:   else
\* 26:     broadcast PREVOTE for nil
\* 27:   step_p <- prevote
\* @type: (Int) => Bool;
UponProposalInPropose(p) ==
  UponProposalInPropose ::
  LET v_cache61 ==
    round[p]
  IN
    /\ (step[p] = "PROPOSE_OF_STEP")
    /\ /\ \E v \in (ValidValues \union InvalidValues):
            /\ ([proposal |-> v,
                 round |-> v_cache61,
                 src |-> Proposer[v_cache61],
                 valid_round |-> -1] \in msgs_propose[v_cache61])
            /\ msgs_prevote' =
                 [msgs_prevote EXCEPT ![v_cache61] =
                   (msgs_prevote[v_cache61] \union {[id |-> (IF /\ (v \in ValidValues)
                                                                /\ \/ (locked_round[p] = -1)
                                                                   \/ (locked_value[p] = v)
                       THEN
                         v
                       ELSE
                         -1),
                       kind |-> "PREVOTE_OF_VOTEKIND",
                       round |-> v_cache61,
                       src |-> p]})]
            /\ step' = [step EXCEPT ![p] = "PREVOTE_OF_STEP"]
            /\ last_action' = "UPON_PROPOSAL_PROPOSE"

\* 28: upon proposal (v, vr) from proposer and 2f+1 prevotes for v in vr
\*     while step_p = propose and 0 <= vr < round_p
\* 29:   if valid(v) and (lockedRound_p <= vr or lockedValue_p = v) then
\* 30:     broadcast PREVOTE for v
\* 31:   else
\* 32:     broadcast PREVOTE for nil
\* 33:   step_p <- prevote
\* @type: (Int) => Bool;
UponProposalInProposeAndPrevote(p) ==
  UponProposalInProposeAndPrevote ::
  LET v_cache62 ==
    round[p]
  IN
    /\ (step[p] = "PROPOSE_OF_STEP")
    /\ /\ \E v \in (ValidValues \union InvalidValues):
            /\ \E vr \in (0)..(MaxRound):
                 /\ (vr >= 0)
                 /\ (vr < v_cache62)
                 /\ LET v_cache64 ==
                      {m63 \in msgs_prevote[vr]: (v = m63.id)}
                    IN
                      /\ ([proposal |-> v,
                           round |-> v_cache62,
                           src |-> Proposer[v_cache62],
                           valid_round |-> vr] \in msgs_propose[v_cache62])
                      /\ (Cardinality(v_cache64) >= ((2 * T) + 1))
                      /\ msgs_prevote' =
                           [msgs_prevote EXCEPT ![v_cache62] =
                             (msgs_prevote[v_cache62] \union {[id |-> (IF /\ (v \in ValidValues)
                                                                          /\ \/ (locked_round[p] <= vr)
                                                                             \/ (locked_value[p] = v)
                                 THEN
                                   v
                                 ELSE
                                   -1),
                                 kind |-> "PREVOTE_OF_VOTEKIND",
                                 round |-> v_cache62,
                                 src |-> p]})]
                      /\ step' = [step EXCEPT ![p] = "PREVOTE_OF_STEP"]
                      /\ last_action' = "UPON_PROPOSAL_PROPOSE_AND_PREVOTE"

\* 34: upon 2f+1 current-round prevotes while step_p = prevote
\* 35:   schedule OnTimeoutPrevote(h_p, round_p)
\*
\* This safety model does not store timers. The transition represents the
\* timeout firing and immediately takes the nil-precommit path.
\* @type: (Int) => Bool;
UponQuorumOfPrevotesAny(p) ==
  UponQuorumOfPrevotesAny ::
  LET v_cache65 ==
    round[p]
  IN
    /\ (step[p] = "PREVOTE_OF_STEP")
    /\ /\ \E my_evidence \in SUBSET msgs_prevote[v_cache65]:
            /\ (Cardinality({v_v66 \in (Corr \union Faulty): (\E v_v67 \in my_evidence: (v_v66 = v_v67.src))}) >= ((2 * T) + 1))
            /\ msgs_precommit' =
                 [msgs_precommit EXCEPT ![v_cache65] =
                   (msgs_precommit[v_cache65] \union {[id |-> -1,
                       kind |-> "PRECOMMIT_OF_VOTEKIND",
                       round |-> v_cache65,
                       src |-> p]})]
            /\ step' = [step EXCEPT ![p] = "PRECOMMIT_OF_STEP"]
            /\ last_action' = "UPON_QUORUM_PREVOTES_ANY"

\* 36: upon proposal (v, *) and 2f+1 current-round prevotes for v
\*     while valid(v) and step_p >= prevote
\* 37:   if step_p = prevote then
\* 38:     lockedValue_p <- v
\* 39:     lockedRound_p <- round_p
\* 40:     broadcast PRECOMMIT for v
\* 41:     step_p <- precommit
\* 42:   validValue_p <- v
\* 43:   validRound_p <- round_p
\* @type: (Int) => Bool;
UponProposalInPrevoteOrCommitAndPrevote(p) ==
  UponProposalInPrevoteOrCommitAndPrevote ::
  LET v_cache68 ==
    round[p]
  IN
    /\ \/ (step[p] = "PREVOTE_OF_STEP")
       \/ (step[p] = "PRECOMMIT_OF_STEP")
    /\ /\ \E v \in ValidValues:
            /\ \E vr \in ((0)..(MaxRound) \union {-1}):
                 LET v_cache70 ==
                   {m69 \in msgs_prevote[v_cache68]: (v = m69.id)}
                 IN
                   /\ ([proposal |-> v,
                        round |-> v_cache68,
                        src |-> Proposer[v_cache68],
                        valid_round |-> vr] \in msgs_propose[v_cache68])
                   /\ (Cardinality(v_cache70) >= ((2 * T) + 1))
                   /\ \/ lab_then(v, vr) ::
                         /\ (step[p] = "PREVOTE_OF_STEP")
                         /\ locked_value' = [locked_value EXCEPT ![p] = v]
                         /\ locked_round' =
                              [locked_round EXCEPT ![p] = v_cache68]
                         /\ msgs_precommit' =
                              [msgs_precommit EXCEPT ![v_cache68] =
                                (msgs_precommit[v_cache68] \union {[id |-> v,
                                    kind |-> "PRECOMMIT_OF_VOTEKIND",
                                    round |-> v_cache68,
                                    src |-> p]})]
                         /\ step' = [step EXCEPT ![p] = "PRECOMMIT_OF_STEP"]
                      \/ lab_else(v, vr) ::
                         ~((step[p] = "PREVOTE_OF_STEP"))
                         /\ UNCHANGED <<step, locked_value, locked_round, msgs_precommit>>
                   /\ valid_value' = [valid_value EXCEPT ![p] = v]
                   /\ valid_round' = [valid_round EXCEPT ![p] = v_cache68]
                   /\ last_action' =
                        "UPON_PROPOSAL_PREVOTE_OR_COMMIT_AND_PREVOTE"

\* 47: upon 2f+1 current-round precommits
\* 48:   schedule OnTimeoutPrecommit(h_p, round_p)
\*
\* This safety model does not store timers. The transition represents the
\* timeout firing and immediately advances to the next modeled round.
\* @type: (Int) => Bool;
UponQuorumOfPrecommitsAny(p) ==
  UponQuorumOfPrecommitsAny ::
  LET v_cache71 ==
    round[p]
  IN
    /\ \E my_evidence \in SUBSET msgs_precommit[v_cache71]:
         /\ (Cardinality({v_v72 \in (Corr \union Faulty): (\E v_v73 \in my_evidence: (v_v72 = v_v73.src))}) >= ((2 * T) + 1))
         /\ ((v_cache71 + 1) \in (0)..(MaxRound))
         /\ (step[p] /= "DECIDED_OF_STEP")
         /\ round' = [round EXCEPT ![p] = (v_cache71 + 1)]
         /\ step' = [step EXCEPT ![p] = "PROPOSE_OF_STEP"]
         /\ last_action' = "UPON_QUORUM_PRECOMMITS_ANY"

\* 49: upon proposal (v, *) and 2f+1 precommits for v while undecided
\* 50:   if valid(v) then
\* 51:     decision_p[h_p] <- v
\* 52:     h_p <- h_p + 1
\* 53:     reset locks, valid value, valid round, and message log
\* 54:     StartRound(0)
\*
\* This one-height model records the decision and moves the process to DECIDED.
\* @type: (Int) => Bool;
UponProposalInPrecommitNoDecision(p) ==
  UponProposalInPrecommitNoDecision ::
  /\ (decision[p] = -1)
  /\ /\ \E v \in ValidValues:
          /\ \E rnd \in (0)..(MaxRound):
               /\ \E vr \in ((0)..(MaxRound) \union {-1}):
                    LET v_cache75 ==
                      {m74 \in msgs_precommit[rnd]: (v = m74.id)}
                    IN
                      /\ ([proposal |-> v,
                           round |-> rnd,
                           src |-> Proposer[rnd],
                           valid_round |-> vr] \in msgs_propose[rnd])
                      /\ (Cardinality(v_cache75) >= ((2 * T) + 1))
                      /\ decision' = [decision EXCEPT ![p] = v]
                      /\ step' = [step EXCEPT ![p] = "DECIDED_OF_STEP"]
                      /\ last_action' = "UPON_PROPOSAL_PRECOMMIT_NO_DECISION"

\* 57: OnTimeoutPropose(height, round)
\* 58:   if height = h_p and round = round_p and step_p = propose then
\* 59:     broadcast PREVOTE for nil
\* 60:     step_p <- prevote
\* @type: (Int) => Bool;
OnTimeoutPropose(p) ==
  OnTimeoutPropose ::
  LET v_cache76 ==
    round[p]
  IN
    /\ (step[p] = "PROPOSE_OF_STEP")
    /\ (p /= Proposer[v_cache76])
    /\ msgs_prevote' =
         [msgs_prevote EXCEPT ![v_cache76] =
           (msgs_prevote[v_cache76] \union {[id |-> -1,
               kind |-> "PREVOTE_OF_VOTEKIND",
               round |-> v_cache76,
               src |-> p]})]
    /\ step' = [step EXCEPT ![p] = "PREVOTE_OF_STEP"]
    /\ last_action' = "ON_TIMEOUT_PROPOSE"

\* 44: upon 2f+1 current-round PREVOTE nil messages while step_p = prevote
\* 45:   broadcast PRECOMMIT for nil
\* 46:   step_p <- precommit
\* @type: (Int) => Bool;
OnQuorumOfNilPrevotes(p) ==
  OnQuorumOfNilPrevotes ::
  LET v_cache77 ==
    round[p]
  IN
    /\ (step[p] = "PREVOTE_OF_STEP")
    /\ LET v_cache79 ==
         {m78 \in msgs_prevote[v_cache77]: (m78.id = -1)}
       IN
         /\ (Cardinality(v_cache79) >= ((2 * T) + 1))
         /\ msgs_precommit' =
              [msgs_precommit EXCEPT ![v_cache77] =
                (msgs_precommit[v_cache77] \union {[id |-> -1,
                    kind |-> "PRECOMMIT_OF_VOTEKIND",
                    round |-> v_cache77,
                    src |-> p]})]
         /\ step' = [step EXCEPT ![p] = "PRECOMMIT_OF_STEP"]
         /\ last_action' = "ON_QUORUM_NIL_PREVOTES"

\* 55: upon f+1 messages from a higher round
\* 56:   StartRound(round)
\* @type: (Int) => Bool;
OnRoundCatchup(p) ==
  OnRoundCatchup ::
  /\ \E rnd \in (0)..(MaxRound):
       /\ \E ev_propose \in SUBSET msgs_propose[rnd]:
            /\ \E ev_prevote \in SUBSET msgs_prevote[rnd]:
                 /\ \E ev_precommit \in SUBSET msgs_precommit[rnd]:
                      /\ (rnd > round[p])
                      /\ (Cardinality((({v_v80 \in (Corr \union Faulty): (\E v_v81 \in ev_propose: (v_v80 = v_v81.src))} \union {v_v82 \in (Corr \union Faulty): (\E v_v83 \in ev_prevote: (v_v82 = v_v83.src))}) \union {v_v84 \in (Corr \union Faulty): (\E v_v85 \in ev_precommit: (v_v84 = v_v85.src))})) >= (T + 1))
                      /\ (step[p] /= "DECIDED_OF_STEP")
                      /\ round' = [round EXCEPT ![p] = rnd]
                      /\ step' = [step EXCEPT ![p] = "PROPOSE_OF_STEP"]
                      /\ last_action' = "ON_ROUND_CATCHUP"

\* Algorithm 1, lines 1-9, adapted to one height.
\* This initializer starts with empty message logs for faulty processes.
Init ==
  /\ round = [v_v0 \in Corr |-> 0]
  /\ step = [v_v1 \in Corr |-> "PROPOSE_OF_STEP"]
  /\ decision = [v_v2 \in Corr |-> -1]
  /\ locked_value = [v_v3 \in Corr |-> -1]
  /\ locked_round = [v_v4 \in Corr |-> -1]
  /\ valid_value = [v_v5 \in Corr |-> -1]
  /\ valid_round = [v_v6 \in Corr |-> -1]
  /\ msgs_propose = [v_v7 \in (0)..(MaxRound) |-> {}]
  /\ msgs_prevote = [v_v8 \in (0)..(MaxRound) |-> {}]
  /\ msgs_precommit = [v_v9 \in (0)..(MaxRound) |-> {}]
  /\ last_action = "INIT"

\* Algorithm 1, lines 1-9, adapted to one height.
\* Extension: the initial message logs may contain arbitrary faulty messages.
InitWithFaults ==
  /\ \E faulty_proposals \in SUBSET {[proposal |-> v_v10[3],
       round |-> v_v10[2],
       src |-> v_v10[1],
       valid_round |-> v_v10[4]]: v_v10 \in (Faulty) \X ((0)..(MaxRound)) \X ((ValidValues \union InvalidValues)) \X (((0)..(MaxRound) \union {-1}))}:
       /\ \E faulty_prevotes \in SUBSET {[id |-> v_v11[3],
            kind |-> "PREVOTE_OF_VOTEKIND",
            round |-> v_v11[2],
            src |-> v_v11[1]]: v_v11 \in (Faulty) \X ((0)..(MaxRound)) \X ((ValidValues \union InvalidValues))}:
            /\ \E faulty_precommits \in SUBSET {[id |-> v_v12[3],
                 kind |-> "PRECOMMIT_OF_VOTEKIND",
                 round |-> v_v12[2],
                 src |-> v_v12[1]]: v_v12 \in (Faulty) \X ((0)..(MaxRound)) \X ((ValidValues \union InvalidValues))}:
                 /\ round = [v_v13 \in Corr |-> 0]
                 /\ step = [v_v14 \in Corr |-> "PROPOSE_OF_STEP"]
                 /\ decision = [v_v15 \in Corr |-> -1]
                 /\ locked_value = [v_v16 \in Corr |-> -1]
                 /\ locked_round = [v_v17 \in Corr |-> -1]
                 /\ valid_value = [v_v18 \in Corr |-> -1]
                 /\ valid_round = [v_v19 \in Corr |-> -1]
                 /\ msgs_propose =
                      [v_v20 \in (0)..(MaxRound) |-> {m21 \in faulty_proposals: (v_v20 = m21.round)}]
                 /\ msgs_prevote =
                      [v_v22 \in (0)..(MaxRound) |-> {m23 \in faulty_prevotes: (v_v22 = m23.round)}]
                 /\ msgs_precommit =
                      [v_v24 \in (0)..(MaxRound) |-> {m25 \in faulty_precommits: (v_v24 = m25.round)}]
                 /\ last_action = "INIT"

\* Choose one correct process and execute one enabled protocol transition.
CorrectStep ==
  /\ \E p \in Corr:
       \/ lab_InsertProposal(p) ::
          InsertProposal(p)
          /\ UNCHANGED <<round, step, decision, locked_value, locked_round, valid_value, valid_round, msgs_prevote, msgs_precommit>>
       \/ lab_UponProposalInPropose(p) ::
          UponProposalInPropose(p)
          /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_precommit>>
       \/ lab_UponProposalInProposeAndPrevote(p) ::
          UponProposalInProposeAndPrevote(p)
          /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_precommit>>
       \/ lab_UponQuorumOfPrevotesAny(p) ::
          UponQuorumOfPrevotesAny(p)
          /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote>>
       \/ lab_UponProposalInPrevoteOrCommitAndPrevote(p) ::
          UponProposalInPrevoteOrCommitAndPrevote(p)
          /\ UNCHANGED <<round, decision, msgs_propose, msgs_prevote>>
       \/ lab_UponQuorumOfPrecommitsAny(p) ::
          UponQuorumOfPrecommitsAny(p)
          /\ UNCHANGED <<decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote, msgs_precommit>>
       \/ lab_UponProposalInPrecommitNoDecision(p) ::
          UponProposalInPrecommitNoDecision(p)
          /\ UNCHANGED <<round, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote, msgs_precommit>>
       \/ lab_OnTimeoutPropose(p) ::
          OnTimeoutPropose(p)
          /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_precommit>>
       \/ lab_OnQuorumOfNilPrevotes(p) ::
          OnQuorumOfNilPrevotes(p)
          /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote>>
       \/ lab_OnRoundCatchup(p) ::
          OnRoundCatchup(p)
          /\ UNCHANGED <<decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote, msgs_precommit>>

\* Inject arbitrary proposal, prevote, and precommit messages by faulty replicas.
FaultyStep ==
  /\ \E r \in (0)..(MaxRound):
       /\ /\ \E fps1 \in SUBSET Faulty:
               /\ \E v1 \in (ValidValues \union InvalidValues):
                    /\ \E vr1 \in ((0)..(MaxRound) \union {-1}):
                         msgs_propose' =
                           [msgs_propose EXCEPT ![r] =
                             (msgs_propose[r] \union {[proposal |-> v1,
                               round |-> r,
                               src |-> v_v53,
                               valid_round |-> vr1]: v_v53 \in fps1})]
       /\ /\ \E fps2 \in SUBSET Faulty:
               /\ \E v2 \in (ValidValues \union InvalidValues):
                    msgs_prevote' =
                      [msgs_prevote EXCEPT ![r] =
                        (msgs_prevote[r] \union {[id |-> v2,
                          kind |-> "PREVOTE_OF_VOTEKIND",
                          round |-> r,
                          src |-> v_v54]: v_v54 \in fps2})]
       /\ /\ \E fps3 \in SUBSET Faulty:
               /\ \E v3 \in (ValidValues \union InvalidValues):
                    msgs_precommit' =
                      [msgs_precommit EXCEPT ![r] =
                        (msgs_precommit[r] \union {[id |-> v3,
                          kind |-> "PRECOMMIT_OF_VOTEKIND",
                          round |-> r,
                          src |-> v_v55]: v_v55 \in fps3})]

\* A system transition: either faulty message injection or a correct step.
Step ==
  \/ lab_faulty_step ::
     FaultyStep
     /\ UNCHANGED <<round, step, decision, locked_value, locked_round, valid_value, valid_round, last_action>>
  \/ lab_correct_step ::
     /\ \E p \in Corr:
          \/ lab_InsertProposal(p) ::
             InsertProposal(p)
             /\ UNCHANGED <<round, step, decision, locked_value, locked_round, valid_value, valid_round, msgs_prevote, msgs_precommit>>
          \/ lab_UponProposalInPropose(p) ::
             UponProposalInPropose(p)
             /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_precommit>>
          \/ lab_UponProposalInProposeAndPrevote(p) ::
             UponProposalInProposeAndPrevote(p)
             /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_precommit>>
          \/ lab_UponQuorumOfPrevotesAny(p) ::
             UponQuorumOfPrevotesAny(p)
             /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote>>
          \/ lab_UponProposalInPrevoteOrCommitAndPrevote(p) ::
             UponProposalInPrevoteOrCommitAndPrevote(p)
             /\ UNCHANGED <<round, decision, msgs_propose, msgs_prevote>>
          \/ lab_UponQuorumOfPrecommitsAny(p) ::
             UponQuorumOfPrecommitsAny(p)
             /\ UNCHANGED <<decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote, msgs_precommit>>
          \/ lab_UponProposalInPrecommitNoDecision(p) ::
             UponProposalInPrecommitNoDecision(p)
             /\ UNCHANGED <<round, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote, msgs_precommit>>
          \/ lab_OnTimeoutPropose(p) ::
             OnTimeoutPropose(p)
             /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_precommit>>
          \/ lab_OnQuorumOfNilPrevotes(p) ::
             OnQuorumOfNilPrevotes(p)
             /\ UNCHANGED <<round, decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote>>
          \/ lab_OnRoundCatchup(p) ::
             OnRoundCatchup(p)
             /\ UNCHANGED <<decision, locked_value, locked_round, valid_value, valid_round, msgs_propose, msgs_prevote, msgs_precommit>>

\* The Tendermint safety property: agreement among correct processes.
Agreement ==
  Agreement ::
  \A v_v86 \in Corr, v_v87 \in Corr: \/ \/ (decision[v_v86] = -1)
                                        \/ (decision[v_v87] = -1)
                                     \/ (decision[v_v86] = decision[v_v87])

\* Protocol validity: correct decisions are valid values or nil.
Validity ==
  Validity ::
  \A v_v88 \in Corr: \/ (decision[v_v88] = -1)
                     \/ (decision[v_v88] \in ValidValues)

IndTypeOk ==
  IndTypeOk ::
  /\ (round \in [Corr -> (0)..(MaxRound)])
  /\ (step \in [Corr -> {"PROPOSE_OF_STEP",
       "PREVOTE_OF_STEP",
       "PRECOMMIT_OF_STEP",
       "DECIDED_OF_STEP"}])
  /\ (decision \in [Corr -> (ValidValues \union {-1})])
  /\ (locked_value \in [Corr -> (ValidValues \union {-1})])
  /\ (locked_round \in [Corr -> ((0)..(MaxRound) \union {-1})])
  /\ (valid_value \in [Corr -> (ValidValues \union {-1})])
  /\ (valid_round \in [Corr -> ((0)..(MaxRound) \union {-1})])
  /\ (DOMAIN msgs_propose = (0)..(MaxRound))
  /\ (\A v_v89 \in (0)..(MaxRound): \A v_v90 \in msgs_propose[v_v89]: (v_v90 \in {[proposal |-> v_v91[3],
             round |-> v_v91[2],
             src |-> v_v91[1],
             valid_round |-> v_v91[4]]: v_v91 \in ((Corr \union Faulty)) \X ((0)..(MaxRound)) \X (((ValidValues \union InvalidValues) \union {-1})) \X (((0)..(MaxRound) \union {-1}))}))
  /\ (\A v_v92 \in DOMAIN msgs_propose: \A v_v93 \in msgs_propose[v_v92]: (v_v92 = v_v93.round))
  /\ (DOMAIN msgs_prevote = (0)..(MaxRound))
  /\ (\A v_v94 \in (0)..(MaxRound): \A v_v95 \in msgs_prevote[v_v94]: (v_v95 \in {[id |-> v_v96[3],
             kind |-> "PREVOTE_OF_VOTEKIND",
             round |-> v_v96[2],
             src |-> v_v96[1]]: v_v96 \in ((Corr \union Faulty)) \X ((0)..(MaxRound)) \X (((ValidValues \union InvalidValues) \union {-1}))}))
  /\ (\A v_v97 \in DOMAIN msgs_prevote: \A v_v98 \in msgs_prevote[v_v97]: (v_v97 = v_v98.round))
  /\ (DOMAIN msgs_precommit = (0)..(MaxRound))
  /\ (\A v_v99 \in (0)..(MaxRound): \A v_v100 \in msgs_precommit[v_v99]: (v_v100 \in {[id |-> v_v101[3],
             kind |-> "PRECOMMIT_OF_VOTEKIND",
             round |-> v_v101[2],
             src |-> v_v101[1]]: v_v101 \in ((Corr \union Faulty)) \X ((0)..(MaxRound)) \X (((ValidValues \union InvalidValues) \union {-1}))}))
  /\ (\A v_v102 \in DOMAIN msgs_precommit: \A v_v103 \in msgs_precommit[v_v102]: (v_v102 = v_v103.round))
  /\ (last_action \in {"INIT",
       "INSERT_PROPOSAL",
       "UPON_PROPOSAL_PROPOSE",
       "UPON_PROPOSAL_PROPOSE_AND_PREVOTE",
       "UPON_QUORUM_PREVOTES_ANY",
       "UPON_PROPOSAL_PREVOTE_OR_COMMIT_AND_PREVOTE",
       "UPON_QUORUM_PRECOMMITS_ANY",
       "UPON_PROPOSAL_PRECOMMIT_NO_DECISION",
       "ON_TIMEOUT_PROPOSE",
       "ON_QUORUM_NIL_PREVOTES",
       "ON_ROUND_CATCHUP"})

\* Use this action as the initial action to reason about inductive invariants
IndInit ==
  /\ \E iround \in [Corr -> (0)..(MaxRound)]:
       /\ \E istep \in [Corr -> {"PROPOSE_OF_STEP",
            "PREVOTE_OF_STEP",
            "PRECOMMIT_OF_STEP",
            "DECIDED_OF_STEP"}]:
            /\ \E idecision \in [Corr -> (ValidValues \union {-1})]:
                 /\ \E ilocked_value \in [Corr -> (ValidValues \union {-1})]:
                      /\ \E ilocked_round \in [Corr -> ((0)..(MaxRound) \union {-1})]:
                           /\ \E ivalid_value \in [Corr -> (ValidValues \union {-1})]:
                                /\ \E ivalid_round \in [Corr -> ((0)..(MaxRound) \union {-1})]:
                                     /\ \E imsgs_propose \in [(0)..(MaxRound) -> SUBSET {[proposal |-> v_v218[3],
                                          round |-> v_v218[2],
                                          src |-> v_v218[1],
                                          valid_round |-> v_v218[4]]: v_v218 \in ((Corr \union Faulty)) \X ((0)..(MaxRound)) \X (((ValidValues \union InvalidValues) \union {-1})) \X (((0)..(MaxRound) \union {-1}))}]:
                                          /\ \E imsgs_prevote \in [(0)..(MaxRound) -> SUBSET {[id |-> v_v219[3],
                                               kind |-> "PREVOTE_OF_VOTEKIND",
                                               round |-> v_v219[2],
                                               src |-> v_v219[1]]: v_v219 \in ((Corr \union Faulty)) \X ((0)..(MaxRound)) \X (((ValidValues \union InvalidValues) \union {-1}))}]:
                                               /\ \E imsgs_precommit \in [(0)..(MaxRound) -> SUBSET {[id |-> v_v220[3],
                                                    kind |-> "PRECOMMIT_OF_VOTEKIND",
                                                    round |-> v_v220[2],
                                                    src |-> v_v220[1]]: v_v220 \in ((Corr \union Faulty)) \X ((0)..(MaxRound)) \X (((ValidValues \union InvalidValues) \union {-1}))}]:
                                                    /\ \E iaction \in {"INIT",
                                                         "INSERT_PROPOSAL",
                                                         "UPON_PROPOSAL_PROPOSE",
                                                         "UPON_PROPOSAL_PROPOSE_AND_PREVOTE",
                                                         "UPON_QUORUM_PREVOTES_ANY",
                                                         "UPON_PROPOSAL_PREVOTE_OR_COMMIT_AND_PREVOTE",
                                                         "UPON_QUORUM_PRECOMMITS_ANY",
                                                         "UPON_PROPOSAL_PRECOMMIT_NO_DECISION",
                                                         "ON_TIMEOUT_PROPOSE",
                                                         "ON_QUORUM_NIL_PREVOTES",
                                                         "ON_ROUND_CATCHUP"}:
                                                         /\ \A v_v221 \in DOMAIN imsgs_propose: \A v_v222 \in imsgs_propose[v_v221]: (v_v221 = v_v222.round)
                                                         /\ \A v_v223 \in DOMAIN imsgs_prevote: \A v_v224 \in imsgs_prevote[v_v223]: (v_v223 = v_v224.round)
                                                         /\ \A v_v225 \in DOMAIN imsgs_precommit: \A v_v226 \in imsgs_precommit[v_v225]: (v_v225 = v_v226.round)
                                                         /\ round = iround
                                                         /\ step = istep
                                                         /\ decision = idecision
                                                         /\ locked_value =
                                                              ilocked_value
                                                         /\ locked_round =
                                                              ilocked_round
                                                         /\ valid_value =
                                                              ivalid_value
                                                         /\ valid_round =
                                                              ivalid_round
                                                         /\ msgs_propose =
                                                              imsgs_propose
                                                         /\ msgs_prevote =
                                                              imsgs_prevote
                                                         /\ msgs_precommit =
                                                              imsgs_precommit
                                                         /\ last_action =
                                                              iaction
                                                         /\ /\ (\A v_v227 \in Corr: /\ /\ \/ (v_v227 = Proposer[iround[v_v227]])
                                                                                          \/ (\A v_v228 \in imsgs_propose[iround[v_v227]]: (v_v227 /= v_v228.src))
                                                                                       /\ \/ (istep[v_v227] = "PREVOTE_OF_STEP")
                                                                                          \/ (istep[v_v227] = "PRECOMMIT_OF_STEP")
                                                                                          \/ (istep[v_v227] = "DECIDED_OF_STEP")
                                                                                          \/ (\A v_v229 \in imsgs_prevote[iround[v_v227]]: (v_v227 /= v_v229.src))
                                                                                       /\ \/ (istep[v_v227] = "PRECOMMIT_OF_STEP")
                                                                                          \/ (istep[v_v227] = "DECIDED_OF_STEP")
                                                                                          \/ (\A v_v230 \in imsgs_precommit[iround[v_v227]]: (v_v227 /= v_v230.src))
                                                                                    /\ (\A v_v232 \in {v_v231 \in (0)..(MaxRound): (v_v231 > iround[v_v227])}: /\ (\A v_v233 \in imsgs_propose[v_v232]: (v_v227 /= v_v233.src))
                                                                                                                                                               /\ (\A v_v234 \in imsgs_prevote[v_v232]: (v_v227 /= v_v234.src))
                                                                                                                                                               /\ (\A v_v235 \in imsgs_precommit[v_v232]: (v_v227 /= v_v235.src))))
                                                            /\ (\A v_v236 \in Corr: ((istep[v_v236] = "PREVOTE_OF_STEP")) => (\E v_v237 \in imsgs_prevote[iround[v_v236]]: /\ (v_v237.id \in ((ValidValues \union InvalidValues) \union {-1}))
                                                                                                                                                                           /\ (v_v236 = v_v237.src)))
                                                            /\ (\A v_v238 \in Corr: ((istep[v_v238] = "PRECOMMIT_OF_STEP")) => (\E v_v239 \in imsgs_precommit[iround[v_v238]]: /\ (v_v239.id \in ((ValidValues \union InvalidValues) \union {-1}))
                                                                                                                                                                               /\ (v_v238 = v_v239.src)))
                                                            /\ (\A v_v240 \in Corr: ((istep[v_v240] = "DECIDED_OF_STEP")) => (\E v_v241 \in (0)..(MaxRound): \E v_v242 \in imsgs_propose[v_v241]: /\ (v_v242.src = Proposer[v_v241])
                                                                                                                                                                                                  /\ (v_v242.proposal = idecision[v_v240])))
                                                            /\ (\A v_v243 \in Corr: ((istep[v_v243] = "DECIDED_OF_STEP")) => (\E v_v244 \in (0)..(MaxRound): (Cardinality({v_v246 \in (Corr \union Faulty): (\E v_v247 \in {v_v245 \in imsgs_precommit[v_v244]: (v_v245.id = idecision[v_v243])}: (v_v246 = v_v247.src))}) >= ((2 * T) + 1))))
                                                            /\ (\A v_v248 \in Corr: ((istep[v_v248] = "DECIDED_OF_STEP") = (idecision[v_v248] \in ValidValues)))
                                                            /\ (\A v_v249 \in Corr: ((ilocked_round[v_v249] = -1) = (ilocked_value[v_v249] = -1)))
                                                            /\ (\A v_v250 \in Corr: ((ivalid_round[v_v250] = -1) = (ivalid_value[v_v250] = -1)))
                                                            /\ (\A v_v251 \in Corr: /\ (ivalid_round[v_v251] <= iround[v_v251])
                                                                                    /\ (ilocked_round[v_v251] <= iround[v_v251]))
                                                            /\ (\A v_v252 \in Corr: ((ivalid_round[v_v252] /= -1)) => ((Cardinality({v_v254 \in (Corr \union Faulty): (\E v_v255 \in {v_v253 \in imsgs_prevote[ivalid_round[v_v252]]: (v_v253.id = ivalid_value[v_v252])}: (v_v254 = v_v255.src))}) >= ((2 * T) + 1))))
                                                            /\ (\A v_v256 \in Corr: ((ilocked_round[v_v256] /= -1)) => (\E v_v257 \in (0)..(MaxRound): /\ (v_v257 <= iround[v_v256])
                                                                                                                                                       /\ (\E v_v258 \in imsgs_precommit[v_v257]: /\ (v_v256 = v_v258.src)
                                                                                                                                                                                                  /\ (v_v258.id = ilocked_value[v_v256]))))
                                                            /\ (\A v_v259 \in Corr: \/ /\ (ilocked_round[v_v259] = -1)
                                                                                       /\ (ilocked_value[v_v259] = -1)
                                                                                       /\ (\A v_v260 \in (0)..(MaxRound): \A v_v261 \in imsgs_precommit[v_v260]: \/ (v_v259 /= v_v261.src)
                                                                                                                                                                 \/ (v_v261.id = -1))
                                                                                    \/ /\ (ilocked_round[v_v259] /= -1)
                                                                                       /\ (ilocked_value[v_v259] /= -1)
                                                                                       /\ (\A v_v262 \in (0)..(MaxRound): \A v_v263 \in imsgs_precommit[v_v262]: \/ \/ (v_v259 /= v_v263.src)
                                                                                                                                                                    \/ (v_v263.round <= ilocked_round[v_v259])
                                                                                                                                                                 \/ (v_v263.id = -1))
                                                                                       /\ (\E v_v264 \in imsgs_precommit[ilocked_round[v_v259]]: /\ (v_v259 = v_v264.src)
                                                                                                                                                 /\ (v_v264.id = ilocked_value[v_v259])))
                                                            /\ (\A v_v265 \in (0)..(MaxRound): \A v_v266 \in imsgs_prevote[v_v265]: \/ (v_v266.src \in Faulty)
                                                                                                                                    \/ (v_v266.id = -1)
                                                                                                                                    \/ /\ (v_v266.id /= -1)
                                                                                                                                       /\ \/ (\E v_v267 \in imsgs_propose[v_v265]: /\ (v_v267.src = Proposer[v_v265])
                                                                                                                                                                                   /\ (v_v267.proposal = v_v266.id)
                                                                                                                                                                                   /\ (v_v267.valid_round = -1))
                                                                                                                                          \/ (\E v_v269 \in {rr268 \in (0)..(MaxRound): (rr268 < v_v265)}: /\ (\E v_v270 \in imsgs_propose[v_v265]: /\ (v_v270.src = Proposer[v_v265])
                                                                                                                                                                                                                                                    /\ (v_v270.proposal = v_v266.id)
                                                                                                                                                                                                                                                    /\ (v_v269 = v_v270.valid_round))
                                                                                                                                                                                                           /\ (Cardinality({v_v272 \in (Corr \union Faulty): (\E v_v273 \in {v_v271 \in imsgs_prevote[v_v269]: (v_v271.id = v_v266.id)}: (v_v272 = v_v273.src))}) >= ((2 * T) + 1))))
                                                            /\ (\A v_v274 \in (0)..(MaxRound): \A v_v275 \in imsgs_precommit[v_v274]: ((v_v275.src \in Corr)) => (\E v_v276 \in imsgs_prevote[v_v274]: (v_v276.src = v_v275.src)))
                                                            /\ (\A v_v277 \in (0)..(MaxRound): \A v_v278 \in imsgs_precommit[v_v277]: ((v_v278.src \in Corr)) => (\/ /\ (v_v278.id \in ValidValues)
                                                                                                                                                                     /\ (Cardinality({v_v280 \in (Corr \union Faulty): (\E v_v281 \in {v_v279 \in imsgs_prevote[v_v277]: (v_v279.id = v_v278.id)}: (v_v280 = v_v281.src))}) >= ((2 * T) + 1))
                                                                                                                                                                  \/ /\ (v_v278.id = -1)
                                                                                                                                                                     /\ (Cardinality({v_v282 \in (Corr \union Faulty): (\E v_v283 \in imsgs_prevote[v_v277]: (v_v282 = v_v283.src))}) >= ((2 * T) + 1))))
                                                            /\ (\A v_v284 \in (0)..(MaxRound): /\ (\E v_v285 \in ValidValues: \E v_v286 \in ((0)..(MaxRound) \union {-1}): \A v_v287 \in imsgs_propose[v_v284]: \/ (v_v287.src \in Faulty)
                                                                                                                                                                                                                \/ /\ /\ (v_v287.src = Proposer[v_v284])
                                                                                                                                                                                                                      /\ (v_v285 = v_v287.proposal)
                                                                                                                                                                                                                   /\ (v_v286 = v_v287.valid_round))
                                                                                               /\ (\A v_v288 \in Corr: \E v_v289 \in (ValidValues \union {-1}): \A v_v290 \in imsgs_prevote[v_v284]: ((v_v288 = v_v290.src)) => ((v_v289 = v_v290.id)))
                                                                                               /\ (\A v_v291 \in Corr: \E v_v292 \in (ValidValues \union {-1}): \A v_v293 \in imsgs_precommit[v_v284]: ((v_v291 = v_v293.src)) => ((v_v292 = v_v293.id))))
                                                            /\ (\A v_v294 \in (0)..(MaxRound), v_v295 \in ValidValues: \/ (Cardinality({v_v297 \in (Corr \union Faulty): (\E v_v298 \in {v_v296 \in imsgs_precommit[v_v294]: (v_v295 = v_v296.id)}: (v_v297 = v_v298.src))}) < ((2 * T) + 1))
                                                                                                                       \/ (\A v_v300 \in {v_v299 \in (0)..(MaxRound): (v_v299 > v_v294)}: \A v_v301 \in (ValidValues \ {v_v295}): (Cardinality({v_v303 \in (Corr \union Faulty): (\E v_v304 \in {v_v302 \in imsgs_prevote[v_v300]: (v_v301 = v_v302.id)}: (v_v303 = v_v304.src))}) < ((2 * T) + 1))))
                                                            /\ (\A v_v305 \in Corr, v_v306 \in (0)..(MaxRound), v_v307 \in ValidValues, v_v308 \in (0)..(MaxRound): (/\ (v_v308 > v_v306)
                                                                                                                                                                     /\ (\E v_v309 \in imsgs_precommit[v_v306]: /\ /\ (v_v305 = v_v309.src)
                                                                                                                                                                                                                   /\ (v_v309.id /= -1)
                                                                                                                                                                                                                /\ (v_v307 /= v_v309.id))
                                                                                                                                                                     /\ (\E v_v310 \in imsgs_prevote[v_v308]: /\ (v_v305 = v_v310.src)
                                                                                                                                                                                                              /\ (v_v307 = v_v310.id))) => (\E v_v312 \in {v_v311 \in (0)..(MaxRound): /\ (v_v311 >= v_v306)
                                                                                                                                                                                                                                                                                       /\ (v_v311 < v_v308)}: (Cardinality({v_v314 \in (Corr \union Faulty): (\E v_v315 \in {v_v313 \in imsgs_prevote[v_v312]: (v_v307 = v_v313.id)}: (v_v314 = v_v315.src))}) >= ((2 * T) + 1))))
                                                            /\ (\A v_v316 \in (0)..(MaxRound): (/\ (Proposer[v_v316] \in Corr)
                                                                                                /\ (\E v_v317 \in imsgs_propose[v_v316]: /\ (v_v317.src = Proposer[v_v316])
                                                                                                                                         /\ (v_v317.valid_round = -1))) => (\A v_v319 \in {v_v318 \in (0)..(MaxRound): (v_v318 < v_v316)}: ~(\E v_v320 \in imsgs_precommit[v_v319]: /\ (v_v320.src = Proposer[v_v316])
                                                                                                                                                                                                                                                                                    /\ (v_v320.id /= -1))))
                                                            /\ (\A v_v321 \in Corr, v_v322 \in (0)..(MaxRound): \/ (v_v322 > iround[v_v321])
                                                                                                                \/ (v_v322 = 0)
                                                                                                                \/ (Cardinality(({v_v325 \in (Corr \union Faulty): (\E v_v326 \in imsgs_prevote[v_v322]: (v_v325 = v_v326.src))} \union {v_v323 \in (Corr \union Faulty): (\E v_v324 \in imsgs_precommit[v_v322]: (v_v323 = v_v324.src))})) >= (T + 1))
                                                                                                                \/ (Cardinality({v_v327 \in (Corr \union Faulty): (\E v_v328 \in imsgs_precommit[(v_v322 - 1)]: (v_v327 = v_v328.src))}) >= ((2 * T) + 1)))
                                                            /\ (\A v_v332 \in (0)..(MaxRound): ((v_v332 < (LET max_candidates_584 ==
                                                                    ({iround[k329]: k329 \in DOMAIN iround} \union {0})
                                                                  IN
                                                                    CHOOSE max_585 \in max_candidates_584: \A max_other_586 \in max_candidates_584: (max_585 >= max_other_586)))) => ((Cardinality({v_v333 \in (Corr \union Faulty): (\E v_v334 \in imsgs_precommit[v_v332]: (v_v333 = v_v334.src))}) >= ((2 * T) + 1))))
                                                            /\ (\A v_v335 \in Corr: ((ivalid_round[v_v335] = iround[v_v335])) => (\/ (istep[v_v335] = "PRECOMMIT_OF_STEP")
                                                                                                                                  \/ (istep[v_v335] = "DECIDED_OF_STEP")))
                                                            /\ (\A v_v336 \in Corr: (ilocked_round[v_v336] <= ivalid_round[v_v336]))
                                                            /\ (\A v_v337 \in Corr: ((ivalid_round[v_v337] /= -1)) => (\E v_v338 \in imsgs_precommit[ivalid_round[v_v337]]: (v_v337 = v_v338.src)))
                                                            /\ (\A v_v339 \in (0)..(MaxRound): \A v_v340 \in imsgs_propose[v_v339]: ((v_v340.src \in Corr)) => ((v_v339 > v_v340.valid_round)))

\* Reduced coverage projection over per-process protocol state.
MinCov ==
  WSMkTuple7(round,
    step,
    decision,
    locked_value,
    locked_round,
    valid_value,
    valid_round)

AllNoFutureMessagesSent ==
  AllNoFutureMessagesSent ::
  \A v_v470 \in Corr: /\ /\ \/ (v_v470 = Proposer[round[v_v470]])
                            \/ (\A v_v471 \in msgs_propose[round[v_v470]]: (v_v470 /= v_v471.src))
                         /\ \/ (step[v_v470] = "PREVOTE_OF_STEP")
                            \/ (step[v_v470] = "PRECOMMIT_OF_STEP")
                            \/ (step[v_v470] = "DECIDED_OF_STEP")
                            \/ (\A v_v472 \in msgs_prevote[round[v_v470]]: (v_v470 /= v_v472.src))
                         /\ \/ (step[v_v470] = "PRECOMMIT_OF_STEP")
                            \/ (step[v_v470] = "DECIDED_OF_STEP")
                            \/ (\A v_v473 \in msgs_precommit[round[v_v470]]: (v_v470 /= v_v473.src))
                      /\ (\A v_v475 \in {v_v474 \in (0)..(MaxRound): (v_v474 > round[v_v470])}: /\ (\A v_v476 \in msgs_propose[v_v475]: (v_v470 /= v_v476.src))
                                                                                                /\ (\A v_v477 \in msgs_prevote[v_v475]: (v_v470 /= v_v477.src))
                                                                                                /\ (\A v_v478 \in msgs_precommit[v_v475]: (v_v470 /= v_v478.src)))

AllIfInPrevoteThenSentPrevote ==
  AllIfInPrevoteThenSentPrevote ::
  \A v_v479 \in Corr: ((step[v_v479] = "PREVOTE_OF_STEP")) => (\E v_v480 \in msgs_prevote[round[v_v479]]: /\ (v_v480.id \in ((ValidValues \union InvalidValues) \union {-1}))
                                                                                                          /\ (v_v479 = v_v480.src))

AllIfInPrecommitThenSentPrecommit ==
  AllIfInPrecommitThenSentPrecommit ::
  \A v_v481 \in Corr: ((step[v_v481] = "PRECOMMIT_OF_STEP")) => (\E v_v482 \in msgs_precommit[round[v_v481]]: /\ (v_v482.id \in ((ValidValues \union InvalidValues) \union {-1}))
                                                                                                              /\ (v_v481 = v_v482.src))

AllIfInDecidedThenReceivedProposal ==
  AllIfInDecidedThenReceivedProposal ::
  \A v_v483 \in Corr: ((step[v_v483] = "DECIDED_OF_STEP")) => (\E v_v484 \in (0)..(MaxRound): \E v_v485 \in msgs_propose[v_v484]: /\ (v_v485.src = Proposer[v_v484])
                                                                                                                                  /\ (v_v485.proposal = decision[v_v483]))

AllIfInDecidedThenReceivedTwoThirds ==
  AllIfInDecidedThenReceivedTwoThirds ::
  \A v_v486 \in Corr: ((step[v_v486] = "DECIDED_OF_STEP")) => (\E v_v487 \in (0)..(MaxRound): (Cardinality({v_v489 \in (Corr \union Faulty): (\E v_v490 \in {v_v488 \in msgs_precommit[v_v487]: (v_v488.id = decision[v_v486])}: (v_v489 = v_v490.src))}) >= ((2 * T) + 1)))

AllIfInDecidedThenValidDecision ==
  AllIfInDecidedThenValidDecision ::
  \A v_v491 \in Corr: ((step[v_v491] = "DECIDED_OF_STEP") = (decision[v_v491] \in ValidValues))

AllLockedRoundIffLockedValue ==
  AllLockedRoundIffLockedValue ::
  \A v_v492 \in Corr: ((locked_round[v_v492] = -1) = (locked_value[v_v492] = -1))

AllValidRoundIffValidValue ==
  AllValidRoundIffValidValue ::
  \A v_v493 \in Corr: ((valid_round[v_v493] = -1) = (valid_value[v_v493] = -1))

AllValidAndLockedRoundBounded ==
  AllValidAndLockedRoundBounded ::
  \A v_v494 \in Corr: /\ (valid_round[v_v494] <= round[v_v494])
                      /\ (locked_round[v_v494] <= round[v_v494])

AllIfValidRoundThenTwoThirdsPrevotes ==
  AllIfValidRoundThenTwoThirdsPrevotes ::
  \A v_v495 \in Corr: ((valid_round[v_v495] /= -1)) => ((Cardinality({v_v497 \in (Corr \union Faulty): (\E v_v498 \in {v_v496 \in msgs_prevote[valid_round[v_v495]]: (v_v496.id = valid_value[v_v495])}: (v_v497 = v_v498.src))}) >= ((2 * T) + 1)))

AllIfLockedRoundThenSentCommit ==
  AllIfLockedRoundThenSentCommit ::
  \A v_v499 \in Corr: ((locked_round[v_v499] /= -1)) => (\E v_v500 \in (0)..(MaxRound): /\ (v_v500 <= round[v_v499])
                                                                                        /\ (\E v_v501 \in msgs_precommit[v_v500]: /\ (v_v499 = v_v501.src)
                                                                                                                                  /\ (v_v501.id = locked_value[v_v499])))

AllLatestPrecommitHasLockedRound ==
  AllLatestPrecommitHasLockedRound ::
  \A v_v502 \in Corr: \/ /\ (locked_round[v_v502] = -1)
                         /\ (locked_value[v_v502] = -1)
                         /\ (\A v_v503 \in (0)..(MaxRound): \A v_v504 \in msgs_precommit[v_v503]: \/ (v_v502 /= v_v504.src)
                                                                                                  \/ (v_v504.id = -1))
                      \/ /\ (locked_round[v_v502] /= -1)
                         /\ (locked_value[v_v502] /= -1)
                         /\ (\A v_v505 \in (0)..(MaxRound): \A v_v506 \in msgs_precommit[v_v505]: \/ \/ (v_v502 /= v_v506.src)
                                                                                                     \/ (v_v506.round <= locked_round[v_v502])
                                                                                                  \/ (v_v506.id = -1))
                         /\ (\E v_v507 \in msgs_precommit[locked_round[v_v502]]: /\ (v_v502 = v_v507.src)
                                                                                 /\ (v_v507.id = locked_value[v_v502]))

AllIfSentPrevoteThenReceivedProposalOrTwoThirds ==
  AllIfSentPrevoteThenReceivedProposalOrTwoThirds ::
  \A v_v508 \in (0)..(MaxRound): \A v_v509 \in msgs_prevote[v_v508]: \/ (v_v509.src \in Faulty)
                                                                     \/ (v_v509.id = -1)
                                                                     \/ /\ (v_v509.id /= -1)
                                                                        /\ \/ (\E v_v510 \in msgs_propose[v_v508]: /\ (v_v510.src = Proposer[v_v508])
                                                                                                                   /\ (v_v510.proposal = v_v509.id)
                                                                                                                   /\ (v_v510.valid_round = -1))
                                                                           \/ (\E v_v512 \in {rr511 \in (0)..(MaxRound): (rr511 < v_v508)}: /\ (\E v_v513 \in msgs_propose[v_v508]: /\ (v_v513.src = Proposer[v_v508])
                                                                                                                                                                                    /\ (v_v513.proposal = v_v509.id)
                                                                                                                                                                                    /\ (v_v512 = v_v513.valid_round))
                                                                                                                                            /\ (Cardinality({v_v515 \in (Corr \union Faulty): (\E v_v516 \in {v_v514 \in msgs_prevote[v_v512]: (v_v514.id = v_v509.id)}: (v_v515 = v_v516.src))}) >= ((2 * T) + 1)))

IfSentPrecommitThenSentPrevote ==
  IfSentPrecommitThenSentPrevote ::
  \A v_v517 \in (0)..(MaxRound): \A v_v518 \in msgs_precommit[v_v517]: ((v_v518.src \in Corr)) => (\E v_v519 \in msgs_prevote[v_v517]: (v_v519.src = v_v518.src))

IfSentPrecommitThenReceivedTwoThirds ==
  IfSentPrecommitThenReceivedTwoThirds ::
  \A v_v520 \in (0)..(MaxRound): \A v_v521 \in msgs_precommit[v_v520]: ((v_v521.src \in Corr)) => (\/ /\ (v_v521.id \in ValidValues)
                                                                                                      /\ (Cardinality({v_v523 \in (Corr \union Faulty): (\E v_v524 \in {v_v522 \in msgs_prevote[v_v520]: (v_v522.id = v_v521.id)}: (v_v523 = v_v524.src))}) >= ((2 * T) + 1))
                                                                                                   \/ /\ (v_v521.id = -1)
                                                                                                      /\ (Cardinality({v_v525 \in (Corr \union Faulty): (\E v_v526 \in msgs_prevote[v_v520]: (v_v525 = v_v526.src))}) >= ((2 * T) + 1)))

AllNoEquivocationByCorrect ==
  AllNoEquivocationByCorrect ::
  \A v_v527 \in (0)..(MaxRound): /\ (\E v_v528 \in ValidValues: \E v_v529 \in ((0)..(MaxRound) \union {-1}): \A v_v530 \in msgs_propose[v_v527]: \/ (v_v530.src \in Faulty)
                                                                                                                                                 \/ /\ /\ (v_v530.src = Proposer[v_v527])
                                                                                                                                                       /\ (v_v528 = v_v530.proposal)
                                                                                                                                                    /\ (v_v529 = v_v530.valid_round))
                                 /\ (\A v_v531 \in Corr: \E v_v532 \in (ValidValues \union {-1}): \A v_v533 \in msgs_prevote[v_v527]: ((v_v531 = v_v533.src)) => ((v_v532 = v_v533.id)))
                                 /\ (\A v_v534 \in Corr: \E v_v535 \in (ValidValues \union {-1}): \A v_v536 \in msgs_precommit[v_v527]: ((v_v534 = v_v536.src)) => ((v_v535 = v_v536.id)))

PrecommitsLockValue ==
  PrecommitsLockValue ::
  \A v_v537 \in (0)..(MaxRound), v_v538 \in ValidValues: \/ (Cardinality({v_v540 \in (Corr \union Faulty): (\E v_v541 \in {v_v539 \in msgs_precommit[v_v537]: (v_v538 = v_v539.id)}: (v_v540 = v_v541.src))}) < ((2 * T) + 1))
                                                         \/ (\A v_v543 \in {v_v542 \in (0)..(MaxRound): (v_v542 > v_v537)}: \A v_v544 \in (ValidValues \ {v_v538}): (Cardinality({v_v546 \in (Corr \union Faulty): (\E v_v547 \in {v_v545 \in msgs_prevote[v_v543]: (v_v544 = v_v545.id)}: (v_v546 = v_v547.src))}) < ((2 * T) + 1)))

\* Per-process support that makes precommits_lock_value inductive. If a correct
\* process precommitted a non-NIL value (!= w) in round r (locking it), then it
\* prevotes w in a later round r2 only if w reached a 2f+1 prevote quorum in some
\* round in [r, r2) -- the only way it could re-lock to w. Quantifiers range over
\* the small Corr/rounds/ValidValues domains; message pools appear only under
\* existentials, keeping the SMT encoding cheap.
PrecommitLocksLaterPrevotes ==
  PrecommitLocksLaterPrevotes ::
  \A v_v548 \in Corr, v_v549 \in (0)..(MaxRound), v_v550 \in ValidValues, v_v551 \in (0)..(MaxRound): (/\ (v_v551 > v_v549)
                                                                                                       /\ (\E v_v552 \in msgs_precommit[v_v549]: /\ /\ (v_v548 = v_v552.src)
                                                                                                                                                    /\ (v_v552.id /= -1)
                                                                                                                                                 /\ (v_v550 /= v_v552.id))
                                                                                                       /\ (\E v_v553 \in msgs_prevote[v_v551]: /\ (v_v548 = v_v553.src)
                                                                                                                                               /\ (v_v550 = v_v553.id))) => (\E v_v555 \in {v_v554 \in (0)..(MaxRound): /\ (v_v554 >= v_v549)
                                                                                                                                                                                                                        /\ (v_v554 < v_v551)}: (Cardinality({v_v557 \in (Corr \union Faulty): (\E v_v558 \in {v_v556 \in msgs_prevote[v_v555]: (v_v550 = v_v556.id)}: (v_v557 = v_v558.src))}) >= ((2 * T) + 1)))

\* A correct proposer that already locked (precommitted a non-NIL value in an
\* earlier round) never sends a fresh proposal (valid_round == NIL): a non-NIL
\* precommit sets valid_value, which never reverts to NIL, so insert_proposal
\* re-proposes it with a non-NIL valid_round.
AllLockedProposerReproposes ==
  AllLockedProposerReproposes ::
  \A v_v559 \in (0)..(MaxRound): (/\ (Proposer[v_v559] \in Corr)
                                  /\ (\E v_v560 \in msgs_propose[v_v559]: /\ (v_v560.src = Proposer[v_v559])
                                                                          /\ (v_v560.valid_round = -1))) => (\A v_v562 \in {v_v561 \in (0)..(MaxRound): (v_v561 < v_v559)}: ~(\E v_v563 \in msgs_precommit[v_v562]: /\ (v_v563.src = Proposer[v_v559])
                                                                                                                                                                                                                    /\ (v_v563.id /= -1)))

\* To be in a round, requires StartRound in the past
AllPastStartRound ==
  AllPastStartRound ::
  \A v_v564 \in Corr, v_v565 \in (0)..(MaxRound): \/ (v_v565 > round[v_v564])
                                                  \/ (v_v565 = 0)
                                                  \/ (Cardinality(({v_v568 \in (Corr \union Faulty): (\E v_v569 \in msgs_prevote[v_v565]: (v_v568 = v_v569.src))} \union {v_v566 \in (Corr \union Faulty): (\E v_v567 \in msgs_precommit[v_v565]: (v_v566 = v_v567.src))})) >= (T + 1))
                                                  \/ (Cardinality({v_v570 \in (Corr \union Faulty): (\E v_v571 \in msgs_precommit[(v_v565 - 1)]: (v_v570 = v_v571.src))}) >= ((2 * T) + 1))

\* A correct process can only be in round r if every earlier round already
\* collected a 2f+1 precommit quorum (the only way the global maximum round
\* advances is upon_quorum_of_precommits_any, which needs 2f+1 precommits in
\* round r-1).
\*
\* The inner constraint does not depend on the process, so instead of quantifying
\* over Corr we take the maximum round reached by any correct process and require
\* the quorum in every round strictly below it.
AllRoundsBelowHavePrecommitQuorum ==
  AllRoundsBelowHavePrecommitQuorum ::
  \A v_v575 \in (0)..(MaxRound): ((v_v575 < (LET max_candidates_587 ==
       ({round[k572]: k572 \in DOMAIN round} \union {0})
     IN
       CHOOSE max_588 \in max_candidates_587: \A max_other_589 \in max_candidates_587: (max_588 >= max_other_589)))) => ((Cardinality({v_v576 \in (Corr \union Faulty): (\E v_v577 \in msgs_precommit[v_v575]: (v_v576 = v_v577.src))}) >= ((2 * T) + 1)))

\* If a correct process set valid_round in the round it is still in, it has
\* already passed PREVOTE: valid_round is only assigned by
\* upon_proposal_in_prevote_or_commit_and_prevote (guard step PREVOTE/PRECOMMIT),
\* which leaves the process in step PRECOMMIT. A round is never revisited and the
\* step only advances within a round, so step must be PRECOMMIT or DECIDED.
\* valid_round == NIL never equals round >= 0, so the NIL case is vacuous.
AllValidInCurrentRoundPrecommitted ==
  AllValidInCurrentRoundPrecommitted ::
  \A v_v578 \in Corr: ((valid_round[v_v578] = round[v_v578])) => (\/ (step[v_v578] = "PRECOMMIT_OF_STEP")
                                                                  \/ (step[v_v578] = "DECIDED_OF_STEP"))

\* locked_* and valid_* are set together when locking (the prevote branch of
\* upon_proposal_in_prevote_or_commit_and_prevote), and valid_round only advances
\* afterwards, so locked_round <= valid_round. NIL_ROUND = -1 makes the unlocked
\* case free and forces valid_round != NIL whenever the process is locked.
AllLockedRoundBelowValidRound ==
  AllLockedRoundBelowValidRound ::
  \A v_v579 \in Corr: (locked_round[v_v579] <= valid_round[v_v579])

\* Setting valid_round = r requires reaching step PREVOTE/PRECOMMIT in round r,
\* after which the process has broadcast a precommit in round r (the prevote branch
\* precommits the value; the precommit branch means it already precommitted).
AllIfValidRoundThenPrecommitted ==
  AllIfValidRoundThenPrecommitted ::
  \A v_v580 \in Corr: ((valid_round[v_v580] /= -1)) => (\E v_v581 \in msgs_precommit[valid_round[v_v580]]: (v_v580 = v_v581.src))

\* A correct proposer broadcasts (insert_proposal) while in step PROPOSE, where
\* valid_round[p] < round[p] (it equals round only from PRECOMMIT on, and is
\* bounded by round). So every proposal from a correct src has valid_round < round.
AllCorrectProposalValidRoundBelowRound ==
  AllCorrectProposalValidRoundBelowRound ::
  \A v_v582 \in (0)..(MaxRound): \A v_v583 \in msgs_propose[v_v582]: ((v_v583.src \in Corr)) => ((v_v582 > v_v583.valid_round))

IndInv ==
  IndInv ::
  /\ AllNoFutureMessagesSent
  /\ AllIfInPrevoteThenSentPrevote
  /\ AllIfInPrecommitThenSentPrecommit
  /\ AllIfInDecidedThenReceivedProposal
  /\ AllIfInDecidedThenReceivedTwoThirds
  /\ AllIfInDecidedThenValidDecision
  /\ AllLockedRoundIffLockedValue
  /\ AllValidRoundIffValidValue
  /\ AllValidAndLockedRoundBounded
  /\ AllIfValidRoundThenTwoThirdsPrevotes
  /\ AllIfLockedRoundThenSentCommit
  /\ AllLatestPrecommitHasLockedRound
  /\ AllIfSentPrevoteThenReceivedProposalOrTwoThirds
  /\ IfSentPrecommitThenSentPrevote
  /\ IfSentPrecommitThenReceivedTwoThirds
  /\ AllNoEquivocationByCorrect
  /\ PrecommitsLockValue
  /\ PrecommitLocksLaterPrevotes
  /\ AllLockedProposerReproposes
  /\ AllPastStartRound
  /\ AllRoundsBelowHavePrecommitQuorum
  /\ AllValidInCurrentRoundPrecommitted
  /\ AllLockedRoundBelowValidRound
  /\ AllIfValidRoundThenPrecommitted
  /\ AllCorrectProposalValidRoundBelowRound

TypedIndInv ==
  TypedIndInv ::
  /\ IndTypeOk
  /\ IndInv

================================================================================